// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4qWMpICaiOOkFsFOkI2GQTMnb239-bPw',
    appId: '1:646165658405:web:bda66c1c8af47c721478cc',
    messagingSenderId: '646165658405',
    projectId: 'mano-mano-dashboard-b7a75',
    authDomain: 'mano-mano-dashboard-b7a75.firebaseapp.com',
    storageBucket: 'mano-mano-dashboard-b7a75.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxi5pum5PTOEdpY7OPXkHBh0deBYupciY',
    appId: '1:646165658405:android:62d86aa6835712ba1478cc',
    messagingSenderId: '646165658405',
    projectId: 'mano-mano-dashboard-b7a75',
    storageBucket: 'mano-mano-dashboard-b7a75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0HpvfSCW8nmHJ83aUthEXVA7C-o7J5tU',
    appId: '1:646165658405:ios:258c6086ccfcbc0e1478cc',
    messagingSenderId: '646165658405',
    projectId: 'mano-mano-dashboard-b7a75',
    storageBucket: 'mano-mano-dashboard-b7a75.firebasestorage.app',
    iosBundleId: 'com.example.manoManoDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0HpvfSCW8nmHJ83aUthEXVA7C-o7J5tU',
    appId: '1:646165658405:ios:258c6086ccfcbc0e1478cc',
    messagingSenderId: '646165658405',
    projectId: 'mano-mano-dashboard-b7a75',
    storageBucket: 'mano-mano-dashboard-b7a75.firebasestorage.app',
    iosBundleId: 'com.example.manoManoDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4qWMpICaiOOkFsFOkI2GQTMnb239-bPw',
    appId: '1:646165658405:web:e44f4055ce42ad631478cc',
    messagingSenderId: '646165658405',
    projectId: 'mano-mano-dashboard-b7a75',
    authDomain: 'mano-mano-dashboard-b7a75.firebaseapp.com',
    storageBucket: 'mano-mano-dashboard-b7a75.firebasestorage.app',
  );
}
